package com.sandrew.publish.model;

import java.io.Serializable;
import java.util.Date;

public class SysDicPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.id
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.create_time
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.is_deleted
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.update_time
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.code
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.is_fixed
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    private Integer isFixed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.name
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.sequence
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.status
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dict_type
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    private String dictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.parent_id
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.description
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dictionary
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.id
     *
     * @return the value of sys_dictionary.id
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.id
     *
     * @param id the value for sys_dictionary.id
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.create_time
     *
     * @return the value of sys_dictionary.create_time
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.create_time
     *
     * @param createTime the value for sys_dictionary.create_time
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.is_deleted
     *
     * @return the value of sys_dictionary.is_deleted
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.is_deleted
     *
     * @param isDeleted the value for sys_dictionary.is_deleted
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.update_time
     *
     * @return the value of sys_dictionary.update_time
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.update_time
     *
     * @param updateTime the value for sys_dictionary.update_time
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.code
     *
     * @return the value of sys_dictionary.code
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.code
     *
     * @param code the value for sys_dictionary.code
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.is_fixed
     *
     * @return the value of sys_dictionary.is_fixed
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public Integer getIsFixed() {
        return isFixed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.is_fixed
     *
     * @param isFixed the value for sys_dictionary.is_fixed
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public void setIsFixed(Integer isFixed) {
        this.isFixed = isFixed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.name
     *
     * @return the value of sys_dictionary.name
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.name
     *
     * @param name the value for sys_dictionary.name
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.sequence
     *
     * @return the value of sys_dictionary.sequence
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.sequence
     *
     * @param sequence the value for sys_dictionary.sequence
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.status
     *
     * @return the value of sys_dictionary.status
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.status
     *
     * @param status the value for sys_dictionary.status
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.dict_type
     *
     * @return the value of sys_dictionary.dict_type
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.dict_type
     *
     * @param dictType the value for sys_dictionary.dict_type
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public void setDictType(String dictType) {
        this.dictType = dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.parent_id
     *
     * @return the value of sys_dictionary.parent_id
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.parent_id
     *
     * @param parentId the value for sys_dictionary.parent_id
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dictionary.description
     *
     * @return the value of sys_dictionary.description
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dictionary.description
     *
     * @param description the value for sys_dictionary.description
     *
     * @mbg.generated Tue Jul 30 15:32:20 CEST 2024
     */
    public void setDescription(String description) {
        this.description = description;
    }
}