package com.sandrew.publish.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TmClientPOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tm_client
     *
     * @mbg.generated Wed Oct 22 15:34:21 CST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tm_client
     *
     * @mbg.generated Wed Oct 22 15:34:21 CST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tm_client
     *
     * @mbg.generated Wed Oct 22 15:34:21 CST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Oct 22 15:34:21 CST 2025
     */
    public TmClientPOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Oct 22 15:34:21 CST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Oct 22 15:34:21 CST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Oct 22 15:34:21 CST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Oct 22 15:34:21 CST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Oct 22 15:34:21 CST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Oct 22 15:34:21 CST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Oct 22 15:34:21 CST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Oct 22 15:34:21 CST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Oct 22 15:34:21 CST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_client
     *
     * @mbg.generated Wed Oct 22 15:34:21 CST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tm_client
     *
     * @mbg.generated Wed Oct 22 15:34:21 CST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andClientIdIsNull() {
            addCriterion("client_id is null");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNotNull() {
            addCriterion("client_id is not null");
            return (Criteria) this;
        }

        public Criteria andClientIdEqualTo(Integer value) {
            addCriterion("client_id =", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotEqualTo(Integer value) {
            addCriterion("client_id <>", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThan(Integer value) {
            addCriterion("client_id >", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("client_id >=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThan(Integer value) {
            addCriterion("client_id <", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThanOrEqualTo(Integer value) {
            addCriterion("client_id <=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdIn(List<Integer> values) {
            addCriterion("client_id in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotIn(List<Integer> values) {
            addCriterion("client_id not in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdBetween(Integer value1, Integer value2) {
            addCriterion("client_id between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotBetween(Integer value1, Integer value2) {
            addCriterion("client_id not between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientNameIsNull() {
            addCriterion("client_name is null");
            return (Criteria) this;
        }

        public Criteria andClientNameIsNotNull() {
            addCriterion("client_name is not null");
            return (Criteria) this;
        }

        public Criteria andClientNameEqualTo(String value) {
            addCriterion("client_name =", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotEqualTo(String value) {
            addCriterion("client_name <>", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameGreaterThan(String value) {
            addCriterion("client_name >", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameGreaterThanOrEqualTo(String value) {
            addCriterion("client_name >=", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameLessThan(String value) {
            addCriterion("client_name <", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameLessThanOrEqualTo(String value) {
            addCriterion("client_name <=", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameLike(String value) {
            addCriterion("client_name like", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotLike(String value) {
            addCriterion("client_name not like", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameIn(List<String> values) {
            addCriterion("client_name in", values, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotIn(List<String> values) {
            addCriterion("client_name not in", values, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameBetween(String value1, String value2) {
            addCriterion("client_name between", value1, value2, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotBetween(String value1, String value2) {
            addCriterion("client_name not between", value1, value2, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientTypeIsNull() {
            addCriterion("client_type is null");
            return (Criteria) this;
        }

        public Criteria andClientTypeIsNotNull() {
            addCriterion("client_type is not null");
            return (Criteria) this;
        }

        public Criteria andClientTypeEqualTo(Integer value) {
            addCriterion("client_type =", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeNotEqualTo(Integer value) {
            addCriterion("client_type <>", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeGreaterThan(Integer value) {
            addCriterion("client_type >", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("client_type >=", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeLessThan(Integer value) {
            addCriterion("client_type <", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeLessThanOrEqualTo(Integer value) {
            addCriterion("client_type <=", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeIn(List<Integer> values) {
            addCriterion("client_type in", values, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeNotIn(List<Integer> values) {
            addCriterion("client_type not in", values, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeBetween(Integer value1, Integer value2) {
            addCriterion("client_type between", value1, value2, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("client_type not between", value1, value2, "clientType");
            return (Criteria) this;
        }

        public Criteria andDeclarePeriodIsNull() {
            addCriterion("declare_period is null");
            return (Criteria) this;
        }

        public Criteria andDeclarePeriodIsNotNull() {
            addCriterion("declare_period is not null");
            return (Criteria) this;
        }

        public Criteria andDeclarePeriodEqualTo(Integer value) {
            addCriterion("declare_period =", value, "declarePeriod");
            return (Criteria) this;
        }

        public Criteria andDeclarePeriodNotEqualTo(Integer value) {
            addCriterion("declare_period <>", value, "declarePeriod");
            return (Criteria) this;
        }

        public Criteria andDeclarePeriodGreaterThan(Integer value) {
            addCriterion("declare_period >", value, "declarePeriod");
            return (Criteria) this;
        }

        public Criteria andDeclarePeriodGreaterThanOrEqualTo(Integer value) {
            addCriterion("declare_period >=", value, "declarePeriod");
            return (Criteria) this;
        }

        public Criteria andDeclarePeriodLessThan(Integer value) {
            addCriterion("declare_period <", value, "declarePeriod");
            return (Criteria) this;
        }

        public Criteria andDeclarePeriodLessThanOrEqualTo(Integer value) {
            addCriterion("declare_period <=", value, "declarePeriod");
            return (Criteria) this;
        }

        public Criteria andDeclarePeriodIn(List<Integer> values) {
            addCriterion("declare_period in", values, "declarePeriod");
            return (Criteria) this;
        }

        public Criteria andDeclarePeriodNotIn(List<Integer> values) {
            addCriterion("declare_period not in", values, "declarePeriod");
            return (Criteria) this;
        }

        public Criteria andDeclarePeriodBetween(Integer value1, Integer value2) {
            addCriterion("declare_period between", value1, value2, "declarePeriod");
            return (Criteria) this;
        }

        public Criteria andDeclarePeriodNotBetween(Integer value1, Integer value2) {
            addCriterion("declare_period not between", value1, value2, "declarePeriod");
            return (Criteria) this;
        }

        public Criteria andOptIdIsNull() {
            addCriterion("opt_id is null");
            return (Criteria) this;
        }

        public Criteria andOptIdIsNotNull() {
            addCriterion("opt_id is not null");
            return (Criteria) this;
        }

        public Criteria andOptIdEqualTo(Integer value) {
            addCriterion("opt_id =", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdNotEqualTo(Integer value) {
            addCriterion("opt_id <>", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdGreaterThan(Integer value) {
            addCriterion("opt_id >", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("opt_id >=", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdLessThan(Integer value) {
            addCriterion("opt_id <", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdLessThanOrEqualTo(Integer value) {
            addCriterion("opt_id <=", value, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdIn(List<Integer> values) {
            addCriterion("opt_id in", values, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdNotIn(List<Integer> values) {
            addCriterion("opt_id not in", values, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdBetween(Integer value1, Integer value2) {
            addCriterion("opt_id between", value1, value2, "optId");
            return (Criteria) this;
        }

        public Criteria andOptIdNotBetween(Integer value1, Integer value2) {
            addCriterion("opt_id not between", value1, value2, "optId");
            return (Criteria) this;
        }

        public Criteria andApproveIdIsNull() {
            addCriterion("approve_id is null");
            return (Criteria) this;
        }

        public Criteria andApproveIdIsNotNull() {
            addCriterion("approve_id is not null");
            return (Criteria) this;
        }

        public Criteria andApproveIdEqualTo(Integer value) {
            addCriterion("approve_id =", value, "approveId");
            return (Criteria) this;
        }

        public Criteria andApproveIdNotEqualTo(Integer value) {
            addCriterion("approve_id <>", value, "approveId");
            return (Criteria) this;
        }

        public Criteria andApproveIdGreaterThan(Integer value) {
            addCriterion("approve_id >", value, "approveId");
            return (Criteria) this;
        }

        public Criteria andApproveIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("approve_id >=", value, "approveId");
            return (Criteria) this;
        }

        public Criteria andApproveIdLessThan(Integer value) {
            addCriterion("approve_id <", value, "approveId");
            return (Criteria) this;
        }

        public Criteria andApproveIdLessThanOrEqualTo(Integer value) {
            addCriterion("approve_id <=", value, "approveId");
            return (Criteria) this;
        }

        public Criteria andApproveIdIn(List<Integer> values) {
            addCriterion("approve_id in", values, "approveId");
            return (Criteria) this;
        }

        public Criteria andApproveIdNotIn(List<Integer> values) {
            addCriterion("approve_id not in", values, "approveId");
            return (Criteria) this;
        }

        public Criteria andApproveIdBetween(Integer value1, Integer value2) {
            addCriterion("approve_id between", value1, value2, "approveId");
            return (Criteria) this;
        }

        public Criteria andApproveIdNotBetween(Integer value1, Integer value2) {
            addCriterion("approve_id not between", value1, value2, "approveId");
            return (Criteria) this;
        }

        public Criteria andClientIctIsNull() {
            addCriterion("client_ict is null");
            return (Criteria) this;
        }

        public Criteria andClientIctIsNotNull() {
            addCriterion("client_ict is not null");
            return (Criteria) this;
        }

        public Criteria andClientIctEqualTo(String value) {
            addCriterion("client_ict =", value, "clientIct");
            return (Criteria) this;
        }

        public Criteria andClientIctNotEqualTo(String value) {
            addCriterion("client_ict <>", value, "clientIct");
            return (Criteria) this;
        }

        public Criteria andClientIctGreaterThan(String value) {
            addCriterion("client_ict >", value, "clientIct");
            return (Criteria) this;
        }

        public Criteria andClientIctGreaterThanOrEqualTo(String value) {
            addCriterion("client_ict >=", value, "clientIct");
            return (Criteria) this;
        }

        public Criteria andClientIctLessThan(String value) {
            addCriterion("client_ict <", value, "clientIct");
            return (Criteria) this;
        }

        public Criteria andClientIctLessThanOrEqualTo(String value) {
            addCriterion("client_ict <=", value, "clientIct");
            return (Criteria) this;
        }

        public Criteria andClientIctLike(String value) {
            addCriterion("client_ict like", value, "clientIct");
            return (Criteria) this;
        }

        public Criteria andClientIctNotLike(String value) {
            addCriterion("client_ict not like", value, "clientIct");
            return (Criteria) this;
        }

        public Criteria andClientIctIn(List<String> values) {
            addCriterion("client_ict in", values, "clientIct");
            return (Criteria) this;
        }

        public Criteria andClientIctNotIn(List<String> values) {
            addCriterion("client_ict not in", values, "clientIct");
            return (Criteria) this;
        }

        public Criteria andClientIctBetween(String value1, String value2) {
            addCriterion("client_ict between", value1, value2, "clientIct");
            return (Criteria) this;
        }

        public Criteria andClientIctNotBetween(String value1, String value2) {
            addCriterion("client_ict not between", value1, value2, "clientIct");
            return (Criteria) this;
        }

        public Criteria andClientVatIsNull() {
            addCriterion("client_vat is null");
            return (Criteria) this;
        }

        public Criteria andClientVatIsNotNull() {
            addCriterion("client_vat is not null");
            return (Criteria) this;
        }

        public Criteria andClientVatEqualTo(String value) {
            addCriterion("client_vat =", value, "clientVat");
            return (Criteria) this;
        }

        public Criteria andClientVatNotEqualTo(String value) {
            addCriterion("client_vat <>", value, "clientVat");
            return (Criteria) this;
        }

        public Criteria andClientVatGreaterThan(String value) {
            addCriterion("client_vat >", value, "clientVat");
            return (Criteria) this;
        }

        public Criteria andClientVatGreaterThanOrEqualTo(String value) {
            addCriterion("client_vat >=", value, "clientVat");
            return (Criteria) this;
        }

        public Criteria andClientVatLessThan(String value) {
            addCriterion("client_vat <", value, "clientVat");
            return (Criteria) this;
        }

        public Criteria andClientVatLessThanOrEqualTo(String value) {
            addCriterion("client_vat <=", value, "clientVat");
            return (Criteria) this;
        }

        public Criteria andClientVatLike(String value) {
            addCriterion("client_vat like", value, "clientVat");
            return (Criteria) this;
        }

        public Criteria andClientVatNotLike(String value) {
            addCriterion("client_vat not like", value, "clientVat");
            return (Criteria) this;
        }

        public Criteria andClientVatIn(List<String> values) {
            addCriterion("client_vat in", values, "clientVat");
            return (Criteria) this;
        }

        public Criteria andClientVatNotIn(List<String> values) {
            addCriterion("client_vat not in", values, "clientVat");
            return (Criteria) this;
        }

        public Criteria andClientVatBetween(String value1, String value2) {
            addCriterion("client_vat between", value1, value2, "clientVat");
            return (Criteria) this;
        }

        public Criteria andClientVatNotBetween(String value1, String value2) {
            addCriterion("client_vat not between", value1, value2, "clientVat");
            return (Criteria) this;
        }

        public Criteria andServiceStartIsNull() {
            addCriterion("service_start is null");
            return (Criteria) this;
        }

        public Criteria andServiceStartIsNotNull() {
            addCriterion("service_start is not null");
            return (Criteria) this;
        }

        public Criteria andServiceStartEqualTo(Date value) {
            addCriterionForJDBCDate("service_start =", value, "serviceStart");
            return (Criteria) this;
        }

        public Criteria andServiceStartNotEqualTo(Date value) {
            addCriterionForJDBCDate("service_start <>", value, "serviceStart");
            return (Criteria) this;
        }

        public Criteria andServiceStartGreaterThan(Date value) {
            addCriterionForJDBCDate("service_start >", value, "serviceStart");
            return (Criteria) this;
        }

        public Criteria andServiceStartGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("service_start >=", value, "serviceStart");
            return (Criteria) this;
        }

        public Criteria andServiceStartLessThan(Date value) {
            addCriterionForJDBCDate("service_start <", value, "serviceStart");
            return (Criteria) this;
        }

        public Criteria andServiceStartLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("service_start <=", value, "serviceStart");
            return (Criteria) this;
        }

        public Criteria andServiceStartIn(List<Date> values) {
            addCriterionForJDBCDate("service_start in", values, "serviceStart");
            return (Criteria) this;
        }

        public Criteria andServiceStartNotIn(List<Date> values) {
            addCriterionForJDBCDate("service_start not in", values, "serviceStart");
            return (Criteria) this;
        }

        public Criteria andServiceStartBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("service_start between", value1, value2, "serviceStart");
            return (Criteria) this;
        }

        public Criteria andServiceStartNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("service_start not between", value1, value2, "serviceStart");
            return (Criteria) this;
        }

        public Criteria andServiceEndIsNull() {
            addCriterion("service_end is null");
            return (Criteria) this;
        }

        public Criteria andServiceEndIsNotNull() {
            addCriterion("service_end is not null");
            return (Criteria) this;
        }

        public Criteria andServiceEndEqualTo(Date value) {
            addCriterionForJDBCDate("service_end =", value, "serviceEnd");
            return (Criteria) this;
        }

        public Criteria andServiceEndNotEqualTo(Date value) {
            addCriterionForJDBCDate("service_end <>", value, "serviceEnd");
            return (Criteria) this;
        }

        public Criteria andServiceEndGreaterThan(Date value) {
            addCriterionForJDBCDate("service_end >", value, "serviceEnd");
            return (Criteria) this;
        }

        public Criteria andServiceEndGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("service_end >=", value, "serviceEnd");
            return (Criteria) this;
        }

        public Criteria andServiceEndLessThan(Date value) {
            addCriterionForJDBCDate("service_end <", value, "serviceEnd");
            return (Criteria) this;
        }

        public Criteria andServiceEndLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("service_end <=", value, "serviceEnd");
            return (Criteria) this;
        }

        public Criteria andServiceEndIn(List<Date> values) {
            addCriterionForJDBCDate("service_end in", values, "serviceEnd");
            return (Criteria) this;
        }

        public Criteria andServiceEndNotIn(List<Date> values) {
            addCriterionForJDBCDate("service_end not in", values, "serviceEnd");
            return (Criteria) this;
        }

        public Criteria andServiceEndBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("service_end between", value1, value2, "serviceEnd");
            return (Criteria) this;
        }

        public Criteria andServiceEndNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("service_end not between", value1, value2, "serviceEnd");
            return (Criteria) this;
        }

        public Criteria andClientTaxNoIsNull() {
            addCriterion("client_tax_no is null");
            return (Criteria) this;
        }

        public Criteria andClientTaxNoIsNotNull() {
            addCriterion("client_tax_no is not null");
            return (Criteria) this;
        }

        public Criteria andClientTaxNoEqualTo(String value) {
            addCriterion("client_tax_no =", value, "clientTaxNo");
            return (Criteria) this;
        }

        public Criteria andClientTaxNoNotEqualTo(String value) {
            addCriterion("client_tax_no <>", value, "clientTaxNo");
            return (Criteria) this;
        }

        public Criteria andClientTaxNoGreaterThan(String value) {
            addCriterion("client_tax_no >", value, "clientTaxNo");
            return (Criteria) this;
        }

        public Criteria andClientTaxNoGreaterThanOrEqualTo(String value) {
            addCriterion("client_tax_no >=", value, "clientTaxNo");
            return (Criteria) this;
        }

        public Criteria andClientTaxNoLessThan(String value) {
            addCriterion("client_tax_no <", value, "clientTaxNo");
            return (Criteria) this;
        }

        public Criteria andClientTaxNoLessThanOrEqualTo(String value) {
            addCriterion("client_tax_no <=", value, "clientTaxNo");
            return (Criteria) this;
        }

        public Criteria andClientTaxNoLike(String value) {
            addCriterion("client_tax_no like", value, "clientTaxNo");
            return (Criteria) this;
        }

        public Criteria andClientTaxNoNotLike(String value) {
            addCriterion("client_tax_no not like", value, "clientTaxNo");
            return (Criteria) this;
        }

        public Criteria andClientTaxNoIn(List<String> values) {
            addCriterion("client_tax_no in", values, "clientTaxNo");
            return (Criteria) this;
        }

        public Criteria andClientTaxNoNotIn(List<String> values) {
            addCriterion("client_tax_no not in", values, "clientTaxNo");
            return (Criteria) this;
        }

        public Criteria andClientTaxNoBetween(String value1, String value2) {
            addCriterion("client_tax_no between", value1, value2, "clientTaxNo");
            return (Criteria) this;
        }

        public Criteria andClientTaxNoNotBetween(String value1, String value2) {
            addCriterion("client_tax_no not between", value1, value2, "clientTaxNo");
            return (Criteria) this;
        }

        public Criteria andClientKbkIsNull() {
            addCriterion("client_kbk is null");
            return (Criteria) this;
        }

        public Criteria andClientKbkIsNotNull() {
            addCriterion("client_kbk is not null");
            return (Criteria) this;
        }

        public Criteria andClientKbkEqualTo(String value) {
            addCriterion("client_kbk =", value, "clientKbk");
            return (Criteria) this;
        }

        public Criteria andClientKbkNotEqualTo(String value) {
            addCriterion("client_kbk <>", value, "clientKbk");
            return (Criteria) this;
        }

        public Criteria andClientKbkGreaterThan(String value) {
            addCriterion("client_kbk >", value, "clientKbk");
            return (Criteria) this;
        }

        public Criteria andClientKbkGreaterThanOrEqualTo(String value) {
            addCriterion("client_kbk >=", value, "clientKbk");
            return (Criteria) this;
        }

        public Criteria andClientKbkLessThan(String value) {
            addCriterion("client_kbk <", value, "clientKbk");
            return (Criteria) this;
        }

        public Criteria andClientKbkLessThanOrEqualTo(String value) {
            addCriterion("client_kbk <=", value, "clientKbk");
            return (Criteria) this;
        }

        public Criteria andClientKbkLike(String value) {
            addCriterion("client_kbk like", value, "clientKbk");
            return (Criteria) this;
        }

        public Criteria andClientKbkNotLike(String value) {
            addCriterion("client_kbk not like", value, "clientKbk");
            return (Criteria) this;
        }

        public Criteria andClientKbkIn(List<String> values) {
            addCriterion("client_kbk in", values, "clientKbk");
            return (Criteria) this;
        }

        public Criteria andClientKbkNotIn(List<String> values) {
            addCriterion("client_kbk not in", values, "clientKbk");
            return (Criteria) this;
        }

        public Criteria andClientKbkBetween(String value1, String value2) {
            addCriterion("client_kbk between", value1, value2, "clientKbk");
            return (Criteria) this;
        }

        public Criteria andClientKbkNotBetween(String value1, String value2) {
            addCriterion("client_kbk not between", value1, value2, "clientKbk");
            return (Criteria) this;
        }

        public Criteria andClientFeeIsNull() {
            addCriterion("client_fee is null");
            return (Criteria) this;
        }

        public Criteria andClientFeeIsNotNull() {
            addCriterion("client_fee is not null");
            return (Criteria) this;
        }

        public Criteria andClientFeeEqualTo(String value) {
            addCriterion("client_fee =", value, "clientFee");
            return (Criteria) this;
        }

        public Criteria andClientFeeNotEqualTo(String value) {
            addCriterion("client_fee <>", value, "clientFee");
            return (Criteria) this;
        }

        public Criteria andClientFeeGreaterThan(String value) {
            addCriterion("client_fee >", value, "clientFee");
            return (Criteria) this;
        }

        public Criteria andClientFeeGreaterThanOrEqualTo(String value) {
            addCriterion("client_fee >=", value, "clientFee");
            return (Criteria) this;
        }

        public Criteria andClientFeeLessThan(String value) {
            addCriterion("client_fee <", value, "clientFee");
            return (Criteria) this;
        }

        public Criteria andClientFeeLessThanOrEqualTo(String value) {
            addCriterion("client_fee <=", value, "clientFee");
            return (Criteria) this;
        }

        public Criteria andClientFeeLike(String value) {
            addCriterion("client_fee like", value, "clientFee");
            return (Criteria) this;
        }

        public Criteria andClientFeeNotLike(String value) {
            addCriterion("client_fee not like", value, "clientFee");
            return (Criteria) this;
        }

        public Criteria andClientFeeIn(List<String> values) {
            addCriterion("client_fee in", values, "clientFee");
            return (Criteria) this;
        }

        public Criteria andClientFeeNotIn(List<String> values) {
            addCriterion("client_fee not in", values, "clientFee");
            return (Criteria) this;
        }

        public Criteria andClientFeeBetween(String value1, String value2) {
            addCriterion("client_fee between", value1, value2, "clientFee");
            return (Criteria) this;
        }

        public Criteria andClientFeeNotBetween(String value1, String value2) {
            addCriterion("client_fee not between", value1, value2, "clientFee");
            return (Criteria) this;
        }

        public Criteria andClientMobileIsNull() {
            addCriterion("client_mobile is null");
            return (Criteria) this;
        }

        public Criteria andClientMobileIsNotNull() {
            addCriterion("client_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andClientMobileEqualTo(String value) {
            addCriterion("client_mobile =", value, "clientMobile");
            return (Criteria) this;
        }

        public Criteria andClientMobileNotEqualTo(String value) {
            addCriterion("client_mobile <>", value, "clientMobile");
            return (Criteria) this;
        }

        public Criteria andClientMobileGreaterThan(String value) {
            addCriterion("client_mobile >", value, "clientMobile");
            return (Criteria) this;
        }

        public Criteria andClientMobileGreaterThanOrEqualTo(String value) {
            addCriterion("client_mobile >=", value, "clientMobile");
            return (Criteria) this;
        }

        public Criteria andClientMobileLessThan(String value) {
            addCriterion("client_mobile <", value, "clientMobile");
            return (Criteria) this;
        }

        public Criteria andClientMobileLessThanOrEqualTo(String value) {
            addCriterion("client_mobile <=", value, "clientMobile");
            return (Criteria) this;
        }

        public Criteria andClientMobileLike(String value) {
            addCriterion("client_mobile like", value, "clientMobile");
            return (Criteria) this;
        }

        public Criteria andClientMobileNotLike(String value) {
            addCriterion("client_mobile not like", value, "clientMobile");
            return (Criteria) this;
        }

        public Criteria andClientMobileIn(List<String> values) {
            addCriterion("client_mobile in", values, "clientMobile");
            return (Criteria) this;
        }

        public Criteria andClientMobileNotIn(List<String> values) {
            addCriterion("client_mobile not in", values, "clientMobile");
            return (Criteria) this;
        }

        public Criteria andClientMobileBetween(String value1, String value2) {
            addCriterion("client_mobile between", value1, value2, "clientMobile");
            return (Criteria) this;
        }

        public Criteria andClientMobileNotBetween(String value1, String value2) {
            addCriterion("client_mobile not between", value1, value2, "clientMobile");
            return (Criteria) this;
        }

        public Criteria andClientLinkmanIsNull() {
            addCriterion("client_linkman is null");
            return (Criteria) this;
        }

        public Criteria andClientLinkmanIsNotNull() {
            addCriterion("client_linkman is not null");
            return (Criteria) this;
        }

        public Criteria andClientLinkmanEqualTo(String value) {
            addCriterion("client_linkman =", value, "clientLinkman");
            return (Criteria) this;
        }

        public Criteria andClientLinkmanNotEqualTo(String value) {
            addCriterion("client_linkman <>", value, "clientLinkman");
            return (Criteria) this;
        }

        public Criteria andClientLinkmanGreaterThan(String value) {
            addCriterion("client_linkman >", value, "clientLinkman");
            return (Criteria) this;
        }

        public Criteria andClientLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("client_linkman >=", value, "clientLinkman");
            return (Criteria) this;
        }

        public Criteria andClientLinkmanLessThan(String value) {
            addCriterion("client_linkman <", value, "clientLinkman");
            return (Criteria) this;
        }

        public Criteria andClientLinkmanLessThanOrEqualTo(String value) {
            addCriterion("client_linkman <=", value, "clientLinkman");
            return (Criteria) this;
        }

        public Criteria andClientLinkmanLike(String value) {
            addCriterion("client_linkman like", value, "clientLinkman");
            return (Criteria) this;
        }

        public Criteria andClientLinkmanNotLike(String value) {
            addCriterion("client_linkman not like", value, "clientLinkman");
            return (Criteria) this;
        }

        public Criteria andClientLinkmanIn(List<String> values) {
            addCriterion("client_linkman in", values, "clientLinkman");
            return (Criteria) this;
        }

        public Criteria andClientLinkmanNotIn(List<String> values) {
            addCriterion("client_linkman not in", values, "clientLinkman");
            return (Criteria) this;
        }

        public Criteria andClientLinkmanBetween(String value1, String value2) {
            addCriterion("client_linkman between", value1, value2, "clientLinkman");
            return (Criteria) this;
        }

        public Criteria andClientLinkmanNotBetween(String value1, String value2) {
            addCriterion("client_linkman not between", value1, value2, "clientLinkman");
            return (Criteria) this;
        }

        public Criteria andClientEmailIsNull() {
            addCriterion("client_email is null");
            return (Criteria) this;
        }

        public Criteria andClientEmailIsNotNull() {
            addCriterion("client_email is not null");
            return (Criteria) this;
        }

        public Criteria andClientEmailEqualTo(String value) {
            addCriterion("client_email =", value, "clientEmail");
            return (Criteria) this;
        }

        public Criteria andClientEmailNotEqualTo(String value) {
            addCriterion("client_email <>", value, "clientEmail");
            return (Criteria) this;
        }

        public Criteria andClientEmailGreaterThan(String value) {
            addCriterion("client_email >", value, "clientEmail");
            return (Criteria) this;
        }

        public Criteria andClientEmailGreaterThanOrEqualTo(String value) {
            addCriterion("client_email >=", value, "clientEmail");
            return (Criteria) this;
        }

        public Criteria andClientEmailLessThan(String value) {
            addCriterion("client_email <", value, "clientEmail");
            return (Criteria) this;
        }

        public Criteria andClientEmailLessThanOrEqualTo(String value) {
            addCriterion("client_email <=", value, "clientEmail");
            return (Criteria) this;
        }

        public Criteria andClientEmailLike(String value) {
            addCriterion("client_email like", value, "clientEmail");
            return (Criteria) this;
        }

        public Criteria andClientEmailNotLike(String value) {
            addCriterion("client_email not like", value, "clientEmail");
            return (Criteria) this;
        }

        public Criteria andClientEmailIn(List<String> values) {
            addCriterion("client_email in", values, "clientEmail");
            return (Criteria) this;
        }

        public Criteria andClientEmailNotIn(List<String> values) {
            addCriterion("client_email not in", values, "clientEmail");
            return (Criteria) this;
        }

        public Criteria andClientEmailBetween(String value1, String value2) {
            addCriterion("client_email between", value1, value2, "clientEmail");
            return (Criteria) this;
        }

        public Criteria andClientEmailNotBetween(String value1, String value2) {
            addCriterion("client_email not between", value1, value2, "clientEmail");
            return (Criteria) this;
        }

        public Criteria andClientAddressIsNull() {
            addCriterion("client_address is null");
            return (Criteria) this;
        }

        public Criteria andClientAddressIsNotNull() {
            addCriterion("client_address is not null");
            return (Criteria) this;
        }

        public Criteria andClientAddressEqualTo(String value) {
            addCriterion("client_address =", value, "clientAddress");
            return (Criteria) this;
        }

        public Criteria andClientAddressNotEqualTo(String value) {
            addCriterion("client_address <>", value, "clientAddress");
            return (Criteria) this;
        }

        public Criteria andClientAddressGreaterThan(String value) {
            addCriterion("client_address >", value, "clientAddress");
            return (Criteria) this;
        }

        public Criteria andClientAddressGreaterThanOrEqualTo(String value) {
            addCriterion("client_address >=", value, "clientAddress");
            return (Criteria) this;
        }

        public Criteria andClientAddressLessThan(String value) {
            addCriterion("client_address <", value, "clientAddress");
            return (Criteria) this;
        }

        public Criteria andClientAddressLessThanOrEqualTo(String value) {
            addCriterion("client_address <=", value, "clientAddress");
            return (Criteria) this;
        }

        public Criteria andClientAddressLike(String value) {
            addCriterion("client_address like", value, "clientAddress");
            return (Criteria) this;
        }

        public Criteria andClientAddressNotLike(String value) {
            addCriterion("client_address not like", value, "clientAddress");
            return (Criteria) this;
        }

        public Criteria andClientAddressIn(List<String> values) {
            addCriterion("client_address in", values, "clientAddress");
            return (Criteria) this;
        }

        public Criteria andClientAddressNotIn(List<String> values) {
            addCriterion("client_address not in", values, "clientAddress");
            return (Criteria) this;
        }

        public Criteria andClientAddressBetween(String value1, String value2) {
            addCriterion("client_address between", value1, value2, "clientAddress");
            return (Criteria) this;
        }

        public Criteria andClientAddressNotBetween(String value1, String value2) {
            addCriterion("client_address not between", value1, value2, "clientAddress");
            return (Criteria) this;
        }

        public Criteria andClientPostcodeIsNull() {
            addCriterion("client_postcode is null");
            return (Criteria) this;
        }

        public Criteria andClientPostcodeIsNotNull() {
            addCriterion("client_postcode is not null");
            return (Criteria) this;
        }

        public Criteria andClientPostcodeEqualTo(String value) {
            addCriterion("client_postcode =", value, "clientPostcode");
            return (Criteria) this;
        }

        public Criteria andClientPostcodeNotEqualTo(String value) {
            addCriterion("client_postcode <>", value, "clientPostcode");
            return (Criteria) this;
        }

        public Criteria andClientPostcodeGreaterThan(String value) {
            addCriterion("client_postcode >", value, "clientPostcode");
            return (Criteria) this;
        }

        public Criteria andClientPostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("client_postcode >=", value, "clientPostcode");
            return (Criteria) this;
        }

        public Criteria andClientPostcodeLessThan(String value) {
            addCriterion("client_postcode <", value, "clientPostcode");
            return (Criteria) this;
        }

        public Criteria andClientPostcodeLessThanOrEqualTo(String value) {
            addCriterion("client_postcode <=", value, "clientPostcode");
            return (Criteria) this;
        }

        public Criteria andClientPostcodeLike(String value) {
            addCriterion("client_postcode like", value, "clientPostcode");
            return (Criteria) this;
        }

        public Criteria andClientPostcodeNotLike(String value) {
            addCriterion("client_postcode not like", value, "clientPostcode");
            return (Criteria) this;
        }

        public Criteria andClientPostcodeIn(List<String> values) {
            addCriterion("client_postcode in", values, "clientPostcode");
            return (Criteria) this;
        }

        public Criteria andClientPostcodeNotIn(List<String> values) {
            addCriterion("client_postcode not in", values, "clientPostcode");
            return (Criteria) this;
        }

        public Criteria andClientPostcodeBetween(String value1, String value2) {
            addCriterion("client_postcode between", value1, value2, "clientPostcode");
            return (Criteria) this;
        }

        public Criteria andClientPostcodeNotBetween(String value1, String value2) {
            addCriterion("client_postcode not between", value1, value2, "clientPostcode");
            return (Criteria) this;
        }

        public Criteria andClientCityIsNull() {
            addCriterion("client_city is null");
            return (Criteria) this;
        }

        public Criteria andClientCityIsNotNull() {
            addCriterion("client_city is not null");
            return (Criteria) this;
        }

        public Criteria andClientCityEqualTo(String value) {
            addCriterion("client_city =", value, "clientCity");
            return (Criteria) this;
        }

        public Criteria andClientCityNotEqualTo(String value) {
            addCriterion("client_city <>", value, "clientCity");
            return (Criteria) this;
        }

        public Criteria andClientCityGreaterThan(String value) {
            addCriterion("client_city >", value, "clientCity");
            return (Criteria) this;
        }

        public Criteria andClientCityGreaterThanOrEqualTo(String value) {
            addCriterion("client_city >=", value, "clientCity");
            return (Criteria) this;
        }

        public Criteria andClientCityLessThan(String value) {
            addCriterion("client_city <", value, "clientCity");
            return (Criteria) this;
        }

        public Criteria andClientCityLessThanOrEqualTo(String value) {
            addCriterion("client_city <=", value, "clientCity");
            return (Criteria) this;
        }

        public Criteria andClientCityLike(String value) {
            addCriterion("client_city like", value, "clientCity");
            return (Criteria) this;
        }

        public Criteria andClientCityNotLike(String value) {
            addCriterion("client_city not like", value, "clientCity");
            return (Criteria) this;
        }

        public Criteria andClientCityIn(List<String> values) {
            addCriterion("client_city in", values, "clientCity");
            return (Criteria) this;
        }

        public Criteria andClientCityNotIn(List<String> values) {
            addCriterion("client_city not in", values, "clientCity");
            return (Criteria) this;
        }

        public Criteria andClientCityBetween(String value1, String value2) {
            addCriterion("client_city between", value1, value2, "clientCity");
            return (Criteria) this;
        }

        public Criteria andClientCityNotBetween(String value1, String value2) {
            addCriterion("client_city not between", value1, value2, "clientCity");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Integer value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Integer value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Integer value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Integer value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Integer value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Integer> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Integer> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Integer value1, Integer value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("create_by like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("create_by not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("update_by like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("update_by not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tm_client
     *
     * @mbg.generated do_not_delete_during_merge Wed Oct 22 15:34:21 CST 2025
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tm_client
     *
     * @mbg.generated Wed Oct 22 15:34:21 CST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}