package com.sandrew.publish.model;

import java.io.Serializable;
import java.util.Date;

public class TmDeptPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_dept.dept_id
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_dept.dept_code
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private String deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_dept.dept_name
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_dept.dept_desc
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private String deptDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_dept.father_dept
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Integer fatherDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_dept.status
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_dept.is_delete
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_dept.create_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_dept.create_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_dept.update_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_dept.update_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tm_dept
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_dept.dept_id
     *
     * @return the value of tm_dept.dept_id
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_dept.dept_id
     *
     * @param deptId the value for tm_dept.dept_id
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_dept.dept_code
     *
     * @return the value of tm_dept.dept_code
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_dept.dept_code
     *
     * @param deptCode the value for tm_dept.dept_code
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_dept.dept_name
     *
     * @return the value of tm_dept.dept_name
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_dept.dept_name
     *
     * @param deptName the value for tm_dept.dept_name
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_dept.dept_desc
     *
     * @return the value of tm_dept.dept_desc
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public String getDeptDesc() {
        return deptDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_dept.dept_desc
     *
     * @param deptDesc the value for tm_dept.dept_desc
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setDeptDesc(String deptDesc) {
        this.deptDesc = deptDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_dept.father_dept
     *
     * @return the value of tm_dept.father_dept
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Integer getFatherDept() {
        return fatherDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_dept.father_dept
     *
     * @param fatherDept the value for tm_dept.father_dept
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setFatherDept(Integer fatherDept) {
        this.fatherDept = fatherDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_dept.status
     *
     * @return the value of tm_dept.status
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_dept.status
     *
     * @param status the value for tm_dept.status
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_dept.is_delete
     *
     * @return the value of tm_dept.is_delete
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_dept.is_delete
     *
     * @param isDelete the value for tm_dept.is_delete
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_dept.create_by
     *
     * @return the value of tm_dept.create_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_dept.create_by
     *
     * @param createBy the value for tm_dept.create_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_dept.create_date
     *
     * @return the value of tm_dept.create_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_dept.create_date
     *
     * @param createDate the value for tm_dept.create_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_dept.update_by
     *
     * @return the value of tm_dept.update_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_dept.update_by
     *
     * @param updateBy the value for tm_dept.update_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_dept.update_date
     *
     * @return the value of tm_dept.update_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_dept.update_date
     *
     * @param updateDate the value for tm_dept.update_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}