package com.sandrew.publish.model;

import java.io.Serializable;
import java.util.Date;

public class TmFilePO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_file.file_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_file.file_name
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_file.file_path
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_file.file_status
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer fileStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_file.is_delete
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_file.create_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_file.create_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_file.update_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_file.update_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tm_file
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_file.file_id
     *
     * @return the value of tm_file.file_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_file.file_id
     *
     * @param fileId the value for tm_file.file_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_file.file_name
     *
     * @return the value of tm_file.file_name
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_file.file_name
     *
     * @param fileName the value for tm_file.file_name
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_file.file_path
     *
     * @return the value of tm_file.file_path
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_file.file_path
     *
     * @param filePath the value for tm_file.file_path
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_file.file_status
     *
     * @return the value of tm_file.file_status
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getFileStatus() {
        return fileStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_file.file_status
     *
     * @param fileStatus the value for tm_file.file_status
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setFileStatus(Integer fileStatus) {
        this.fileStatus = fileStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_file.is_delete
     *
     * @return the value of tm_file.is_delete
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_file.is_delete
     *
     * @param isDelete the value for tm_file.is_delete
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_file.create_by
     *
     * @return the value of tm_file.create_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_file.create_by
     *
     * @param createBy the value for tm_file.create_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_file.create_date
     *
     * @return the value of tm_file.create_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_file.create_date
     *
     * @param createDate the value for tm_file.create_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_file.update_by
     *
     * @return the value of tm_file.update_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_file.update_by
     *
     * @param updateBy the value for tm_file.update_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_file.update_date
     *
     * @return the value of tm_file.update_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_file.update_date
     *
     * @param updateDate the value for tm_file.update_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}