package com.sandrew.publish.model;

import java.io.Serializable;
import java.util.Date;

public class TmPostPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_post.post_id
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_post.post_code
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_post.post_name
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private String postName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_post.post_desc
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private String postDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_post.dept_id
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_post.type
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_post.status
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_post.is_delete
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_post.create_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_post.create_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_post.update_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_post.update_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tm_post
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_post.post_id
     *
     * @return the value of tm_post.post_id
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_post.post_id
     *
     * @param postId the value for tm_post.post_id
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_post.post_code
     *
     * @return the value of tm_post.post_code
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_post.post_code
     *
     * @param postCode the value for tm_post.post_code
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_post.post_name
     *
     * @return the value of tm_post.post_name
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public String getPostName() {
        return postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_post.post_name
     *
     * @param postName the value for tm_post.post_name
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setPostName(String postName) {
        this.postName = postName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_post.post_desc
     *
     * @return the value of tm_post.post_desc
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public String getPostDesc() {
        return postDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_post.post_desc
     *
     * @param postDesc the value for tm_post.post_desc
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setPostDesc(String postDesc) {
        this.postDesc = postDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_post.dept_id
     *
     * @return the value of tm_post.dept_id
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_post.dept_id
     *
     * @param deptId the value for tm_post.dept_id
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_post.type
     *
     * @return the value of tm_post.type
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_post.type
     *
     * @param type the value for tm_post.type
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_post.status
     *
     * @return the value of tm_post.status
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_post.status
     *
     * @param status the value for tm_post.status
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_post.is_delete
     *
     * @return the value of tm_post.is_delete
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_post.is_delete
     *
     * @param isDelete the value for tm_post.is_delete
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_post.create_by
     *
     * @return the value of tm_post.create_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_post.create_by
     *
     * @param createBy the value for tm_post.create_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_post.create_date
     *
     * @return the value of tm_post.create_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_post.create_date
     *
     * @param createDate the value for tm_post.create_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_post.update_by
     *
     * @return the value of tm_post.update_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_post.update_by
     *
     * @param updateBy the value for tm_post.update_by
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_post.update_date
     *
     * @return the value of tm_post.update_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_post.update_date
     *
     * @param updateDate the value for tm_post.update_date
     *
     * @mbg.generated Tue Jul 30 15:45:44 CEST 2024
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}