package com.sandrew.publish.model;

import java.io.Serializable;
import java.util.Date;

public class TmTaskPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.task_id
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.client_id
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Integer clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.task_type
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Integer taskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.task_status
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Integer taskStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.doc_file
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Integer docFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.doc_archive_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Date docArchiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.bank_notes_file
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Integer bankNotesFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.bank_notes_archive_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Date bankNotesArchiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.self_exam_file
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Integer selfExamFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.self_exam_archive_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Date selfExamArchiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.draft_file
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Integer draftFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.draft_create_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Date draftCreateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.dir_rej_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Date dirRejDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.dir_rej_cmnt
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private String dirRejCmnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.cli_rej_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Date cliRejDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.cli_rej_cmnt
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private String cliRejCmnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.is_fetch_doc
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Integer isFetchDoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.is_delete
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.create_by
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.create_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.update_by
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_task.update_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tm_task
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.task_id
     *
     * @return the value of tm_task.task_id
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.task_id
     *
     * @param taskId the value for tm_task.task_id
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.client_id
     *
     * @return the value of tm_task.client_id
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.client_id
     *
     * @param clientId the value for tm_task.client_id
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.task_type
     *
     * @return the value of tm_task.task_type
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.task_type
     *
     * @param taskType the value for tm_task.task_type
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.task_status
     *
     * @return the value of tm_task.task_status
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Integer getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.task_status
     *
     * @param taskStatus the value for tm_task.task_status
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setTaskStatus(Integer taskStatus) {
        this.taskStatus = taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.doc_file
     *
     * @return the value of tm_task.doc_file
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Integer getDocFile() {
        return docFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.doc_file
     *
     * @param docFile the value for tm_task.doc_file
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setDocFile(Integer docFile) {
        this.docFile = docFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.doc_archive_date
     *
     * @return the value of tm_task.doc_archive_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Date getDocArchiveDate() {
        return docArchiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.doc_archive_date
     *
     * @param docArchiveDate the value for tm_task.doc_archive_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setDocArchiveDate(Date docArchiveDate) {
        this.docArchiveDate = docArchiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.bank_notes_file
     *
     * @return the value of tm_task.bank_notes_file
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Integer getBankNotesFile() {
        return bankNotesFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.bank_notes_file
     *
     * @param bankNotesFile the value for tm_task.bank_notes_file
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setBankNotesFile(Integer bankNotesFile) {
        this.bankNotesFile = bankNotesFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.bank_notes_archive_date
     *
     * @return the value of tm_task.bank_notes_archive_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Date getBankNotesArchiveDate() {
        return bankNotesArchiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.bank_notes_archive_date
     *
     * @param bankNotesArchiveDate the value for tm_task.bank_notes_archive_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setBankNotesArchiveDate(Date bankNotesArchiveDate) {
        this.bankNotesArchiveDate = bankNotesArchiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.self_exam_file
     *
     * @return the value of tm_task.self_exam_file
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Integer getSelfExamFile() {
        return selfExamFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.self_exam_file
     *
     * @param selfExamFile the value for tm_task.self_exam_file
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setSelfExamFile(Integer selfExamFile) {
        this.selfExamFile = selfExamFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.self_exam_archive_date
     *
     * @return the value of tm_task.self_exam_archive_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Date getSelfExamArchiveDate() {
        return selfExamArchiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.self_exam_archive_date
     *
     * @param selfExamArchiveDate the value for tm_task.self_exam_archive_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setSelfExamArchiveDate(Date selfExamArchiveDate) {
        this.selfExamArchiveDate = selfExamArchiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.draft_file
     *
     * @return the value of tm_task.draft_file
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Integer getDraftFile() {
        return draftFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.draft_file
     *
     * @param draftFile the value for tm_task.draft_file
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setDraftFile(Integer draftFile) {
        this.draftFile = draftFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.draft_create_date
     *
     * @return the value of tm_task.draft_create_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Date getDraftCreateDate() {
        return draftCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.draft_create_date
     *
     * @param draftCreateDate the value for tm_task.draft_create_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setDraftCreateDate(Date draftCreateDate) {
        this.draftCreateDate = draftCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.dir_rej_date
     *
     * @return the value of tm_task.dir_rej_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Date getDirRejDate() {
        return dirRejDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.dir_rej_date
     *
     * @param dirRejDate the value for tm_task.dir_rej_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setDirRejDate(Date dirRejDate) {
        this.dirRejDate = dirRejDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.dir_rej_cmnt
     *
     * @return the value of tm_task.dir_rej_cmnt
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public String getDirRejCmnt() {
        return dirRejCmnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.dir_rej_cmnt
     *
     * @param dirRejCmnt the value for tm_task.dir_rej_cmnt
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setDirRejCmnt(String dirRejCmnt) {
        this.dirRejCmnt = dirRejCmnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.cli_rej_date
     *
     * @return the value of tm_task.cli_rej_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Date getCliRejDate() {
        return cliRejDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.cli_rej_date
     *
     * @param cliRejDate the value for tm_task.cli_rej_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setCliRejDate(Date cliRejDate) {
        this.cliRejDate = cliRejDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.cli_rej_cmnt
     *
     * @return the value of tm_task.cli_rej_cmnt
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public String getCliRejCmnt() {
        return cliRejCmnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.cli_rej_cmnt
     *
     * @param cliRejCmnt the value for tm_task.cli_rej_cmnt
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setCliRejCmnt(String cliRejCmnt) {
        this.cliRejCmnt = cliRejCmnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.is_fetch_doc
     *
     * @return the value of tm_task.is_fetch_doc
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Integer getIsFetchDoc() {
        return isFetchDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.is_fetch_doc
     *
     * @param isFetchDoc the value for tm_task.is_fetch_doc
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setIsFetchDoc(Integer isFetchDoc) {
        this.isFetchDoc = isFetchDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.is_delete
     *
     * @return the value of tm_task.is_delete
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.is_delete
     *
     * @param isDelete the value for tm_task.is_delete
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.create_by
     *
     * @return the value of tm_task.create_by
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.create_by
     *
     * @param createBy the value for tm_task.create_by
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.create_date
     *
     * @return the value of tm_task.create_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.create_date
     *
     * @param createDate the value for tm_task.create_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.update_by
     *
     * @return the value of tm_task.update_by
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.update_by
     *
     * @param updateBy the value for tm_task.update_by
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_task.update_date
     *
     * @return the value of tm_task.update_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_task.update_date
     *
     * @param updateDate the value for tm_task.update_date
     *
     * @mbg.generated Wed Dec 04 19:29:10 CET 2024
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}