package com.sandrew.publish.model;

import java.io.Serializable;
import java.util.Date;

public class TtMailTemplatePO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_template.template_id
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    private Integer templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_template.template_name
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_template.template_subject
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    private String templateSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_template.template_status
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    private Integer templateStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_template.is_delete
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_template.create_by
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_template.create_date
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_template.update_by
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_template.update_date
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_template.template_content
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    private String templateContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_mail_template
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_template.template_id
     *
     * @return the value of tt_mail_template.template_id
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_template.template_id
     *
     * @param templateId the value for tt_mail_template.template_id
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_template.template_name
     *
     * @return the value of tt_mail_template.template_name
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_template.template_name
     *
     * @param templateName the value for tt_mail_template.template_name
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_template.template_subject
     *
     * @return the value of tt_mail_template.template_subject
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public String getTemplateSubject() {
        return templateSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_template.template_subject
     *
     * @param templateSubject the value for tt_mail_template.template_subject
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public void setTemplateSubject(String templateSubject) {
        this.templateSubject = templateSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_template.template_status
     *
     * @return the value of tt_mail_template.template_status
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public Integer getTemplateStatus() {
        return templateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_template.template_status
     *
     * @param templateStatus the value for tt_mail_template.template_status
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public void setTemplateStatus(Integer templateStatus) {
        this.templateStatus = templateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_template.is_delete
     *
     * @return the value of tt_mail_template.is_delete
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_template.is_delete
     *
     * @param isDelete the value for tt_mail_template.is_delete
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_template.create_by
     *
     * @return the value of tt_mail_template.create_by
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_template.create_by
     *
     * @param createBy the value for tt_mail_template.create_by
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_template.create_date
     *
     * @return the value of tt_mail_template.create_date
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_template.create_date
     *
     * @param createDate the value for tt_mail_template.create_date
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_template.update_by
     *
     * @return the value of tt_mail_template.update_by
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_template.update_by
     *
     * @param updateBy the value for tt_mail_template.update_by
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_template.update_date
     *
     * @return the value of tt_mail_template.update_date
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_template.update_date
     *
     * @param updateDate the value for tt_mail_template.update_date
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_template.template_content
     *
     * @return the value of tt_mail_template.template_content
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public String getTemplateContent() {
        return templateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_template.template_content
     *
     * @param templateContent the value for tt_mail_template.template_content
     *
     * @mbg.generated Wed Jan 15 11:41:02 CET 2025
     */
    public void setTemplateContent(String templateContent) {
        this.templateContent = templateContent;
    }
}