package com.sandrew.publish.model;

import java.io.Serializable;
import java.util.Date;

public class TtMailLogPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_log.mail_log_id
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    private Integer mailLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_log.process_id
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    private Integer processId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_log.sender_id
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    private Integer senderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_log.recipient_email
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    private String recipientEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_log.attachment
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    private Integer attachment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_log.send_time
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_log.create_by
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_log.create_date
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_log.update_by
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_log.update_date
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_mail_log.email_content
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    private String emailContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_mail_log
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_log.mail_log_id
     *
     * @return the value of tt_mail_log.mail_log_id
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public Integer getMailLogId() {
        return mailLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_log.mail_log_id
     *
     * @param mailLogId the value for tt_mail_log.mail_log_id
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public void setMailLogId(Integer mailLogId) {
        this.mailLogId = mailLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_log.process_id
     *
     * @return the value of tt_mail_log.process_id
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public Integer getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_log.process_id
     *
     * @param processId the value for tt_mail_log.process_id
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public void setProcessId(Integer processId) {
        this.processId = processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_log.sender_id
     *
     * @return the value of tt_mail_log.sender_id
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public Integer getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_log.sender_id
     *
     * @param senderId the value for tt_mail_log.sender_id
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public void setSenderId(Integer senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_log.recipient_email
     *
     * @return the value of tt_mail_log.recipient_email
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public String getRecipientEmail() {
        return recipientEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_log.recipient_email
     *
     * @param recipientEmail the value for tt_mail_log.recipient_email
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public void setRecipientEmail(String recipientEmail) {
        this.recipientEmail = recipientEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_log.attachment
     *
     * @return the value of tt_mail_log.attachment
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public Integer getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_log.attachment
     *
     * @param attachment the value for tt_mail_log.attachment
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public void setAttachment(Integer attachment) {
        this.attachment = attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_log.send_time
     *
     * @return the value of tt_mail_log.send_time
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_log.send_time
     *
     * @param sendTime the value for tt_mail_log.send_time
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_log.create_by
     *
     * @return the value of tt_mail_log.create_by
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_log.create_by
     *
     * @param createBy the value for tt_mail_log.create_by
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_log.create_date
     *
     * @return the value of tt_mail_log.create_date
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_log.create_date
     *
     * @param createDate the value for tt_mail_log.create_date
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_log.update_by
     *
     * @return the value of tt_mail_log.update_by
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_log.update_by
     *
     * @param updateBy the value for tt_mail_log.update_by
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_log.update_date
     *
     * @return the value of tt_mail_log.update_date
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_log.update_date
     *
     * @param updateDate the value for tt_mail_log.update_date
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_mail_log.email_content
     *
     * @return the value of tt_mail_log.email_content
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public String getEmailContent() {
        return emailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_mail_log.email_content
     *
     * @param emailContent the value for tt_mail_log.email_content
     *
     * @mbg.generated Sun Dec 29 13:48:33 CET 2024
     */
    public void setEmailContent(String emailContent) {
        this.emailContent = emailContent;
    }
}