package com.sandrew.publish.model;

import java.io.Serializable;
import java.util.Date;

public class TtTaskProcessPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task_process.process_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer processId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task_process.task_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task_process.opt_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Date optDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task_process.opt_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private String optBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task_process.task_status_from
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer taskStatusFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task_process.task_status_to
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer taskStatusTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task_process.comment
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task_process.file_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task_process.is_delete
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task_process.create_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task_process.create_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task_process.update_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_task_process.update_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_task_process
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task_process.process_id
     *
     * @return the value of tt_task_process.process_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task_process.process_id
     *
     * @param processId the value for tt_task_process.process_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setProcessId(Integer processId) {
        this.processId = processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task_process.task_id
     *
     * @return the value of tt_task_process.task_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task_process.task_id
     *
     * @param taskId the value for tt_task_process.task_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task_process.opt_date
     *
     * @return the value of tt_task_process.opt_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Date getOptDate() {
        return optDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task_process.opt_date
     *
     * @param optDate the value for tt_task_process.opt_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setOptDate(Date optDate) {
        this.optDate = optDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task_process.opt_by
     *
     * @return the value of tt_task_process.opt_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public String getOptBy() {
        return optBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task_process.opt_by
     *
     * @param optBy the value for tt_task_process.opt_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setOptBy(String optBy) {
        this.optBy = optBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task_process.task_status_from
     *
     * @return the value of tt_task_process.task_status_from
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getTaskStatusFrom() {
        return taskStatusFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task_process.task_status_from
     *
     * @param taskStatusFrom the value for tt_task_process.task_status_from
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setTaskStatusFrom(Integer taskStatusFrom) {
        this.taskStatusFrom = taskStatusFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task_process.task_status_to
     *
     * @return the value of tt_task_process.task_status_to
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getTaskStatusTo() {
        return taskStatusTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task_process.task_status_to
     *
     * @param taskStatusTo the value for tt_task_process.task_status_to
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setTaskStatusTo(Integer taskStatusTo) {
        this.taskStatusTo = taskStatusTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task_process.comment
     *
     * @return the value of tt_task_process.comment
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task_process.comment
     *
     * @param comment the value for tt_task_process.comment
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task_process.file_id
     *
     * @return the value of tt_task_process.file_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task_process.file_id
     *
     * @param fileId the value for tt_task_process.file_id
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task_process.is_delete
     *
     * @return the value of tt_task_process.is_delete
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task_process.is_delete
     *
     * @param isDelete the value for tt_task_process.is_delete
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task_process.create_by
     *
     * @return the value of tt_task_process.create_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task_process.create_by
     *
     * @param createBy the value for tt_task_process.create_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task_process.create_date
     *
     * @return the value of tt_task_process.create_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task_process.create_date
     *
     * @param createDate the value for tt_task_process.create_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task_process.update_by
     *
     * @return the value of tt_task_process.update_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task_process.update_by
     *
     * @param updateBy the value for tt_task_process.update_by
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_task_process.update_date
     *
     * @return the value of tt_task_process.update_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_task_process.update_date
     *
     * @param updateDate the value for tt_task_process.update_date
     *
     * @mbg.generated Wed Dec 25 18:39:15 CET 2024
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}