package com.sandrew.publish.mapper;

import com.sandrew.publish.model.TmRolePO;
import com.sandrew.publish.model.TmRolePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmRolePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    long countByExample(TmRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    int deleteByExample(TmRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    int insert(TmRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    int insertSelective(TmRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    List<TmRolePO> selectByExample(TmRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    TmRolePO selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    int updateByExampleSelective(@Param("record") TmRolePO record, @Param("example") TmRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    int updateByExample(@Param("record") TmRolePO record, @Param("example") TmRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    int updateByPrimaryKeySelective(TmRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_role
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    int updateByPrimaryKey(TmRolePO record);
}