package com.sandrew.publish.mapper;

import com.sandrew.publish.model.TmUserPO;
import com.sandrew.publish.model.TmUserPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmUserPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    long countByExample(TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    int deleteByExample(TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    int insert(TmUserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    int insertSelective(TmUserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    List<TmUserPO> selectByExample(TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    TmUserPO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    int updateByExampleSelective(@Param("record") TmUserPO record, @Param("example") TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    int updateByExample(@Param("record") TmUserPO record, @Param("example") TmUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    int updateByPrimaryKeySelective(TmUserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_user
     *
     * @mbg.generated Fri Feb 13 16:15:40 CST 2026
     */
    int updateByPrimaryKey(TmUserPO record);
}