##########################
#     Druid DataSource   #
##########################
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.url=jdbc:mysql://localhost:3306/database?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/general?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.username=username
spring.datasource.hikari.password=password
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.maxLifetime=60000
spring.datasource.hikari.registerMbeans=true

# management.security.enabled=false
#embed tomcat configuration
server.port=8080
#server.port=${random.int[1024,9080]} random port between 1024-9080
server.servlet.context-path=/
server.tomcat.uri-encoding=UTF-8

##########################
#   REDIS configuration  #
##########################
spring.data.redis.database=0
# Redis host
spring.data.redis.host=localhost
# Redis port
spring.data.redis.port=6379
# Redis password\uFF08default:blank\uFF09
#spring.data.redis.username=default
spring.data.redis.password=redispass
spring.data.redis.timeout=60s
#spring.redis.sentinel.master=mymaster
#spring.redis.sentinel.nodes=${REDIS_SERVER_NODE_1},${REDIS_SERVER_NODE_2},${REDIS_SERVER_NODE_3}
# max configuration, negative is not limited
spring.data.redis.lettuce.pool.max-active=500
# max wait, limit
spring.data.redis.lettuce.pool.max-wait=-1ms
# max idle
spring.data.redis.lettuce.pool.max-idle=100
# min idle
spring.data.redis.lettuce.pool.min-idle=20

####################################
#      jackson configuration       #
####################################
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+1

####################################
#  upload path limit configuration #
####################################
file.local.path=/foo/bar/

####################################
#      logback configuration       #
####################################
logging.file.path=./logs
logging.file.name=publish.log

###########################################
#    Sending email switch configuration   #
###########################################
neplus.email.send.switch=true